interface=wlan0
driver=nl80211
ieee80211n=1
ssid=test-97
hw_mode=g
channel=6
wpa=2
wpa_key_mgmt=WPA-EAP
wpa_pairwise=CCMP
rsn_pairwise=CCMP
ieee8021x=1
eap_server=1
wmm_enabled=1
eapol_key_index_workaround=0
eap_user_file=/soft/0.2/tools/hostapd/aarch64/hostapd.eap_user
ca_cert=/soft/0.2/tools/hostapd/aarch64/ca.pem
server_cert=/soft/0.2/tools/hostapd/aarch64/server.pem
private_key=/soft/0.2/tools/hostapd/aarch64/server.key
private_key_passwd=jizhi@123
auth_algs=1
wpa_passphrase=12345678
macaddr_acl=0
ignore_broadcast_ssid=0
